application: phillycarshare-api-kwawatu
version: 1
runtime: python
api_version: 1

handlers:

- url: /test.*
  login: admin
  script: gaeunit.py

- url: /login.*
  script: pcs/appengine_app.py
  secure: always

- url: /session.*
  script: pcs/appengine_app.py
  secure: optional

- url: /styles
  static_dir: styles

- url: /cookies
  script: pcs/input/wsgi/login.py

- url: /.*
  script: pcs/appengine_app.py
  secure: never

