application: phillycarshare-api-kwawatu
version: 1
runtime: python
api_version: 1

handlers:

- url: /test.*
  login: admin
  script: gaeunit.py

- url: /login.*
  script: pcs/input/wsgi/login.py
  secure: always

- url: /session.*
  script: pcs/input/wsgi/session.py

- url: /newreservation.*
  script: pcs/input/wsgi/newreservation.py

- url: /vehicles.*
  script: pcs/input/wsgi/vehicles.py

- url: /locations.*
  script: pcs/input/wsgi/locations.py

- url: /styles
  static_dir: styles

- url: /cookies
  script: pcs/input/wsgi/login.py

