application: phillycarshare-processor
version: 1
runtime: python
api_version: 1

handlers:

- url: /test.*
  login: admin
  script: gaeunit.py

- url: /login
  script: pcs/wsgi/login.py

- url: /newreservation
  script: pcs/wsgi/newreservation.py

- url: /cookies
  script: pcs/wsgi/login.py

