application: phillycarshare-processor
version: 1
runtime: python
api_version: 1

handlers:

- url: /test.*
  login: admin
  script: gaeunit.py

- url: /login
  script: pcs/input/wsgi/login.py

- url: /session
  script: pcs/input/wsgi/session.py

- url: /newreservation
  script: pcs/input/wsgi/newreservation.py

- url: /cookies
  script: pcs/input/wsgi/login.py

