from pcs.wsgi_handlers.appengine import _AppEngineBasedHandler

from pcs.wsgi_handlers.reservations import ReservationsHandler
from pcs.wsgi_handlers.reservations import ReservationHandler
from pcs.wsgi_handlers.reservations import ReservationsHtmlHandler
from pcs.wsgi_handlers.reservations import ReservationHtmlHandler
from pcs.wsgi_handlers.reservations import ReservationEditorHtmlHandler
from pcs.wsgi_handlers.reservations import ReservationsJsonHandler as _BaseReservationsJsonHandler

class ReservationsJsonHandler (_AppEngineBasedHandler, _BaseReservationsJsonHandler):
    pass
